### ISSUE TITLE
In the dropdown, V3 is listed but always bounces back to V2

### ISSUE THREAD

**Issue by wwilliams69** [MicrosoftDocs/PowerShell-Docs-PSGet#100]
### Type of issue

Missing information

### Feedback

When viewing the documentation, the listbox at the top left of the page shows a dropdown for versions.  If V3 is selected, V2 is shown.

### Page URL

https://learn.microsoft.com/en-us/powershell/module/packagemanagement/find-package?view=powershellget-2.x&viewFallbackFrom=powershellget-3.x

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs-PSGet/blob/main/powershell-gallery/powershellget-2.x/PackageManagement/Find-Package.md

### Author

@sdwheeler

### Document Id

032aff72-0cd8-5d8a-5207-1d9303249217

**Comment by sdwheeler** [comment]
This is expected behavior. The `Find-Package` is only available in the PowerShellGet/PackageManagement v2 module.
