### ISSUE TITLE
Arguments are incorrect

### ISSUE THREAD

**Issue by wwilliams69** [MicrosoftDocs/PowerShell-Docs-PSGet#101]
### Type of issue

Code doesn't work

### Feedback

Currently using Visual Studio Enterprise 2022, version 17.4.4.  Using the package manager host V6.4.0.111, the Find-Package command does not show the -IncludePrerelease option.  The documentation shows -AllowPrereleaseVersions, which is not recognized.  It seems the version and docs are out of sync.  Install-Package -Name parameter is not recognized either.  

### Page URL

https://learn.microsoft.com/en-us/powershell/module/packagemanagement/find-package?view=powershellget-2.x&viewFallbackFrom=powershellget-3.x

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs-PSGet/blob/main/powershell-gallery/powershellget-2.x/PackageManagement/Find-Package.md

### Author

@sdwheeler

### Document Id

032aff72-0cd8-5d8a-5207-1d9303249217

**Comment by sdwheeler** [comment]
The cmdlets in the VS Package Manager come from the Nuget module, not the Package Management module.
This is explained in https://learn.microsoft.com/en-us/powershell/module/packagemanagement/?view=powershellget-2.x.

> The commands contained in the PackageManagement module are different than the commands provided by the NuGet module in the Package Manager Console of Visual Studio. Each module has commands that are not available in the other. Commands with the same name differ in their specific arguments. For more information, see the [PowerShell reference](https://learn.microsoft.com/en-us/nuget/reference/powershell-reference) documentation for the Package Manager Console of Visual Studio.
