### ISSUE TITLE
Get-InstalledModule Command Not Working Remotely

### ISSUE THREAD

**Issue by PawarAjay8487** [MicrosoftDocs/PowerShell-Docs-PSGet#120]
### Type of issue

Code doesn't work

### Feedback

There seems to be some issue with the PowerShell Command Get-InstalledModule. E.g When I log in locally to a Windows server (PowerShell 5.1) and execute command Get-InstalledModule -Name Az it works fine but when I remote into the same server using Enter-PSSession or New-PSSession and run the same command, it fails with the error can no convert null to a system.datetime

![image](https://github.com/MicrosoftDocs/PowerShell-Docs-PSGet/assets/48758839/b543fb18-235e-4a37-b42c-7503a7dfebb2)

On Further troubleshooting, we found that this seems to be an issue with the PowerShell psmodule.psm1 file.

Somehow highlighted command in the below screenshot is not working when called remotely.

![image](https://github.com/MicrosoftDocs/PowerShell-Docs-PSGet/assets/48758839/e89749c4-32cc-4bfe-943a-6bdd98ac89ff)

Here are the lines in the psmodule.psm1 file which might be causing actual issue

![image](https://github.com/MicrosoftDocs/PowerShell-Docs-PSGet/assets/48758839/54595765-4465-4d4b-a75a-095de924e802)

### Page URL

https://learn.microsoft.com/en-us/powershell/module/powershellget/get-installedmodule?view=powershellget-3.x

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs-PSGet/blob/main/powershell-gallery/powershellget-3.x/PowerShellGet/Get-InstalledModule.md

### Author

@sdwheeler

### Document Id

d5816093-327c-2598-9e58-7fd92e89e4a0

**Comment by sdwheeler** [comment]
This repository is for PowerShell core documentation. You seem to be describing a possible issue with PowerShellGet.

Please [file an issue][1] with the PowerShell team.

[1]: https://github.com/PowerShell/PSResourceGet/issues/new/choose
