### ISSUE TITLE
Section 508

### ISSUE THREAD

**Issue by Carthanr** [MicrosoftDocs/PowerShell-Docs-PSGet#138]
### Type of issue

Other (describe below)

### Feedback

Can you provide a product VPAT for both **Windows PowerShell 7.4 LTS** and **Azure Az Powershell Module 11.5**?

### Page URL

https://learn.microsoft.com/en-us/powershell/gallery/faqs?view=powershellget-3.x

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs-PSGet/blob/main/powershell-gallery/docs-conceptual/faqs.yml

### Author

@sdwheeler

### Document Id

c38e827d-db68-3fd7-e1ef-6607a12f375c

**Comment by sdwheeler** [comment]
I don't know what you mean by a "product VPAT". What does this have to do with the PowerShell Gallery?

**Comment by Carthanr** [comment]
My question was directed towards 'accessibility' features when using MS PowerShell 7.4 LTS and Azure Az Powershell Module 11.5.  Is there any documentation that points to that option?  Please let me know if this is not the right portal to direct this question.  Thanks for your assistance.

**Comment by sdwheeler** [comment]
Microsoft publishes Accessibility Conformance Reports at https://www.microsoft.com/accessibility/conformance-reports. You can search by product.

**Comment by Carthanr** [comment]
The link and information you provided is very helpful.  Thank you for your assistance.
