### ISSUE TITLE
Add guidance in using the latest module versions and removing old module versions

### ISSUE THREAD

**Issue by MarcoJanse** [MicrosoftDocs/PowerShell-Docs-PSGet#140]
### Type of issue

Missing information

### Feedback

The documentation lists in the description the following:

> By default, Update-PSResource installs the latest version of the package and any of its dependencies without deleting the older versions installed.

In my opinion this documentation should then also explain how to deal with old versions.

I have also noticed that the new version is not automatically used, unless you import it using `Import-Module -Name <moduleName> -Version <versionNumber> -Force` 

Can the documentation be please updated in regards to handle multiple module versions?

### Page URL

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.psresourceget/update-psresource?view=powershellget-3.x

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs-PSGet/blob/main/powershell-gallery/powershellget-3.x/Microsoft.PowerShell.PSResourceGet/Update-PSResource.md

### Author

@sdwheeler

### Document Id

9dc601c8-18da-76e6-2075-3b02fe7ea451

**Comment by sdwheeler** [comment]
There has been no change in either of these behaviors.
- The commands to install or update a module have never imported the new module. Also, depending on the module, you may need to start a new PowerShell session before you can import the new version.
- Old versions have never been deleted when you install a newer version. You have to manually delete them.
