### ISSUE TITLE
Mrs. Abalkjahl

### ISSUE THREAD

**Issue by jolethalanford** [MicrosoftDocs/PowerShell-Docs-PSGet#143]
### Type of issue

Code doesn't work

### Feedback

I would like to prominent and thank the coulees for the company to aid and assist all functions.

### Page URL

https://learn.microsoft.com/en-us/powershell/module/packagemanagement/?view=powershellget-2.x

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs-PSGet/blob/main/powershell-gallery/powershellget-2.x/PackageManagement/PackageManagement.md

### Author

@sdwheeler

### Document Id

8bf8e4b9-5901-2e34-166a-0e2f71c95de4

**Comment by sdwheeler** [comment]
This issue appears to be spam, which is a violation of our Code of Conduct.
