### ISSUE TITLE
0s

### ISSUE THREAD

**Issue by s643sync** [MicrosoftDocs/PowerShell-Docs-PSGet#147]
### Type of issue

Typo

### Feedback

Install-Module -Name Microsoft.WinGet.DSC -AllowPrerelease

### Page URL

https://learn.microsoft.com/en-us/powershell/module/powershellget/?view=powershellget-3.x

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs-PSGet/blob/main/powershell-gallery/powershellget-3.x/PowerShellGet/PowerShellGet.md

### Author

@sdwheeler

### Document Id

daa87746-e39e-f33c-203c-095d8f203629

**Comment by sdwheeler** [comment]
This feedback is not actionable.
