### ISSUE TITLE
ترخيص ويندوز وامن ويندوز

### ISSUE THREAD

**Issue by aliashour203040** [MicrosoftDocs/PowerShell-Docs-PSGet#155]
### Type of issue

Typo

### Feedback

تنشيط ويندوز وانتهاء الترخيص قريبا ولا يفتح امن ويندوز
![لقطة الشاشة 2024-09-12 043123](https://github.com/user-attachments/assets/8f4a051a-eaac-4e3e-a51e-3f26da0ec6b8)
![لقطة الشاشة 2024-09-12 043150](https://github.com/user-attachments/assets/9905c0b4-079b-4db1-b958-219c14109bcf)
![لقطة الشاشة 2024-09-12 043204](https://github.com/user-attachments/assets/f010fbcc-266e-4f22-94e3-00210eb305ea)
![لقطة شاشة 2024-09-11 151223](https://github.com/user-attachments/assets/4282cd1d-d4cf-4413-b070-ce42780a0313)

### Page URL

https://learn.microsoft.com/en-us/powershell/gallery/getting-started?view=powershellget-3.x

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs-PSGet/blob/main/powershell-gallery/docs-conceptual/getting-started.md

### Author

@sdwheeler

### Document Id

e2d85e36-9a69-0595-90ff-604753e4aa42

**Comment by sdwheeler** [comment]
This repository is for PowerShell core documentation. You seem to be looking for support, which we can't provide here.

I suggest you try posting your issue with context in one of the available [community support forums][1].

[1]: https://docs.microsoft.com/powershell/scripting/community/community-support
