### ISSUE TITLE
Section Nework Access for Powershell Gallery: addition needed

### ISSUE THREAD

**Issue by Martijn-or** [MicrosoftDocs/PowerShell-Docs-PSGet#171]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the module on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Version

v1, v2, v3

### Links

https://learn.microsoft.com/en-us/powershell/gallery/getting-started

### Summary

Network access section was very useful to configure our firewall but we did have to add more hosts to get it to work. 

### Details

We saw `onegetcdn.ec.azureedge.net` in the logs. After we added that some things still did not work. Ended up adding `*.azureedge.net` and we could succesfully install modules from the PowerShell Gallery after that, but we would rather not whitelist the entire `.azureedge.net` domain. 

### Suggested Fix

What is the complete set of hosts required to install modules from PowerShell Gallery?

**Comment by sdwheeler** [comment]
Hosts required for package discovery and download:

- `onegetcdn.azureedge.net` - CDN hostname used by the PackageManagement module
- `powershellgallery.azureedge.net` and `psg-prod-eastus.azureedge.net` - CDN hostnames used by the
  PowerShellGet and Microsoft.PowerShell.PSResourceGet modules
