### ISSUE TITLE
Better document how to use credential persistence in Register-PSResourceRepository

### ISSUE THREAD

**Issue by SydneyhSmith** [MicrosoftDocs/PowerShell-Docs-PSGet#23]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Document new `Get-Foo` cmdlet" instead of "New cmdlet."

### Version

v3

### Summary

I am happy to provide the PR but wanted to track this item, I would love to better document how to use persistent credentials in PowerShellGet v3, this is what I put in the blog post when we announcement the feature (the actual docs don't need to be as verbose) 
## Getting started
For this example I am going to be using SecretStore to store my credentials for an Artifactory repository. This can be repeated with any SecretManagement extension vault, and with any repository. First, I need to make sure I have a SecretManagement vault set up, with my credential stored. 
```
PS C:\Users > Get-SecretInfo
Name          Type         VaultName
----          ----         ---------
jFrogCred     PSCredential SecretStore
```
Then I can create a PSCredentialInfo object to pass into my PSResourceRepository registration, to create this I pass in the name of the vault and the name of the secret.
```
$credentialInfo = New-Object Microsoft.PowerShell.PowerShellGet.UtilClasses.PSCredentialInfo ("SecretStore", "jfrogCred")
```
Now I am ready to register the PSResourceRepository, I will pass in a friendly name, a URI for the repository, and the CredentialInfo. I also use the -Trusted switch because I will be controlling what gets published to the repository.
```
Register-PSResourceRepository -Name artifactory `
-URI " https://<name>.jfrog.io/artifactory/api/nuget/v3/<Repository-Name>
-Trusted `
-CredentialInfo $credentialInfo 
```
Now I can run Get-PSResourceRepository to see my registered repositories
```
PS C:\Users > Get-PSResourceRepository

Name        Uri                                                                                     Trusted Priority
----        ---                                                                                     ------- --------
artifactory https://<name>.jfrog.io/artifactory/api/nuget/v3/<Repository-Name>                      True    50      
PSGallery   https://www.powershellgallery.com/api/v2                                                False   50  
````
If the repository is empty you are going to want to begin by publishing to it. I have saved my API key for publishing to the repository in my SecretStore.
```
Publish-PSResource -Path .\Get-Hello\ -Repository artifactory -ApiKey (Get-Secret jfrogPublish)
```
Now I can find and install PSResources from my repository without needing to provide a credential at each call.

```
PS C:\Users> Find-PSResource -Name Get-Hello -Repository artifactory

Name      Version Prerelease Repository  Description
----      ------- ---------- ----------  -----------
Get-Hello 0.0.2.0            artifactory test module

PS C:\Users> Install-PSResource Get-Hello
```

### Content Type

Concept

**Comment by sdwheeler** [comment]
@SydneyhSmith We have examples for this in the existing docs:

- https://learn.microsoft.com/powershell/module/powershellget/set-psresourcerepository?view=powershellget-3.x#example-4
- https://learn.microsoft.com/powershell/module/powershellget/register-psresourcerepository?view=powershellget-3.x#example-4

Do you want more than this?
