### ISSUE TITLE
Question about 'working with local psrepositorie' documentation

### ISSUE THREAD

**Issue by LaurentDardenne** [MicrosoftDocs/PowerShell-Docs-PSGet#53]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Document new `Get-Foo` cmdlet" instead of "New cmdlet."

### Version

v2, v3

### Summary

For a [fileshare](https://learn.microsoft.com/en-us/powershell/gallery/how-to/working-with-local-psrepositories?view=powershellget-2.x) it is indicated as a disadvantage _"Metadata used by PowerShellGet isn't available"_.

What does this imply in how cmdlets work ? Are they impacted by this absence?

Is this documentation recent?

In my opinion the [Register-PSRepository](https://learn.microsoft.com/en-us/powershell/module/powershellget/register-psrepository?view=powershellget-2.x) documentation should contain a link to this document ('working with local psrepository').

### Content Type

Cmdlet Reference, About Topic, Concept, How-to

### Related Articles

https://learn.microsoft.com/en-us/powershell/gallery/how-to/working-with-local-psrepositories?view=powershellget-2.x

https://learn.microsoft.com/en-us/powershell/module/powershellget/register-psrepository?view=powershellget-2.x

**Comment by sdwheeler** [comment]
This may not be accurate anymore. I have tested with PowerShellGet 2.2.5 and Microsoft.PowerShell.PSResourceGet 0.5.23-beta23. I am able to see all the metadata and search by Tag with both versions.

**Comment by LaurentDardenne** [comment]
Thank you.

I want to know if the [behavior of Find-Module](https://github.com/PowerShell/PowerShellGetv2/issues/697#issuecomment-1653459282) is different for a repository server (Nuget) and for a local repository (fileshare/filesystem) ?
Reading the cited documentation I have a doubt...
