### ISSUE TITLE
Typo in closing brackets

### ISSUE THREAD

**Issue by belibug** [MicrosoftDocs/PowerShell-Docs-PSGet#82]
### Type of issue

Typo

### Feedback

Typo in [Example 3](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.psresourceget/find-psresource?view=powershellget-3.x#example-3) of Find-PSResource cmdlet docs. 

Line 3 in the provided example code has wrong pair of brackets.

Error
```
Version = '(0.9.0.0, 1.2.0.0]'
``` 

Correct format
```
Version = '[0.9.0.0, 1.2.0.0]'
```

### Page URL

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.psresourceget/find-psresource?view=powershellget-3.x

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs-PSGet/blob/main/powershell-gallery/powershellget-3.x/Microsoft.PowerShell.PSResourceGet/Find-PSResource.md

### Author

sdwheeler

### Document Id

7ef96250-0201-c91b-e432-3955e7e91ff8

**Comment by sdwheeler** [comment]
@belibug The example is correct. Please read the documentation for the **Version** parameter and the linked documentation for [NuGet version ranges](https://learn.microsoft.com/nuget/concepts/package-versioning#version-ranges).

The range used in the example `Version = '(0.9.0.0, 1.2.0.0]'` evaluates as `0.9.0.0 < Version <= 1.2.0.0`.
