### ISSUE TITLE
PSResourceGet Article needs updating for 7.4

### ISSUE THREAD

**Issue by JustinGrote** [MicrosoftDocs/PowerShell-Docs-PSGet#94]
### Type of issue

Outdated article

### Feedback

This article should now state that 7.4 ships with PSResourceGet (instead of will ship), and under `Current Release` specify the GA version as well.

### Page URL

https://learn.microsoft.com/en-us/powershell/gallery/powershellget/overview?view=powershellget-3.x

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs-PSGet/blob/main/powershell-gallery/docs-conceptual/powershellget/overview.md

### Author

@sdwheeler

### Document Id

1e997d87-e342-1cab-6e95-f3329580d928

**Comment by sdwheeler** [comment]
> Also @sdwheeler FYI looks like your Github Actions need some repair

Yeah, they changed some permissions at the org level and broke our automation.
