### ISSUE TITLE
hyperlinks & text inside docs-conceptual 3.0 not updated for PSResourceGet

### ISSUE THREAD

**Issue by no-identd** [MicrosoftDocs/PowerShell-Docs-PSGet#97]
### Type of issue

Other (describe below)

### Feedback

https://github.com/MicrosoftDocs/PowerShell-Docs-PSGet/pull/95 didn't exactly fix this (and it couldn't exactly, could it, given that PSResourceGet 3.0 isn't GA yet, so I don't mean this as a dig/criticism/smth like that!), but (given the previous parenthetical remark) it didn't seem appropriate to request a reopen of #94 for this, so, new issue it is. For an obvious example of the issue, see [https://learn.microsoft.com/en-us/powershell/gallery/concepts/publishing-guidelines?view=powershellget-3.x#use-powershellget-to-publish](https://learn.microsoft.com/en-us/powershell/gallery/concepts/publishing-guidelines?view=powershellget-3.x#use-powershellget-to-publish), where it's very obvious because PSResourceGet unifies script publishing and module publishing into one,  but it's all over the place, e.g. Test-ScriptFileInfo (old) vs Test-PSScriptFileInfo (new).

If I had the time, I'd write a brief script to find all references pointing to to identify passages to update, but I (partially due to this issue preventing me from linking the appropriate documentation for this) lack it, sorry.

### Page URL

https://learn.microsoft.com/en-us/powershell/gallery/how-to/publishing-packages/publishing-a-package?view=powershellget-3.x

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs-PSGet/blob/main/powershell-gallery/docs-conceptual/how-to/publishing-packages/publishing-a-package.md

### Author

@sdwheeler

### Document Id

7d90c798-c39f-6654-dbb1-23638a91021f

**Comment by sdwheeler** [comment]
PSResourceGet is GA. There is only one version of the conceptual documentation for the Gallery. Selecting a different version does not change the Gallery documentation, or any of the conceptual documentation. The version selector only changes the cmdlet reference.

We will update the Gallery documentation to reference the new cmdlets sometime in the future.
