### ISSUE TITLE
First available version not provided

### ISSUE THREAD

**Issue by Liturgist** [MicrosoftDocs/PowerShell-Docs-PSGet#98]
### Type of issue

Missing information

### Feedback

Please include the PowerShell version in which this command is available; both for Windows PowerShell and PowerShell Core.

### Page URL

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.psresourceget/find-psresource?view=powershellget-3.x

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs-PSGet/blob/main/powershell-gallery/powershellget-3.x/Microsoft.PowerShell.PSResourceGet/Find-PSResource.md

### Author

@sdwheeler

### Document Id

7ef96250-0201-c91b-e432-3955e7e91ff8

**Comment by sdwheeler** [comment]
The module is installable in Windows PowerShell 5.1 and higher. The module shipped with PowerShell 7.4, as documented in the 7.4 release notes.

**Comment by Liturgist** [comment]
> The module is installable in Windows PowerShell 5.1 and higher. The module shipped with PowerShell 7.4, as documented in the 7.4 release notes.

This information needs to be on or directly accessible from the command description page. Yes, finding out the earliest version on each platform (Windows PowerShell, PowerShell Core Windows, Linux, Mac) that the command is available is needed.
